### ISSUE TITLE
Problem in generating the keops formula

### ISSUE THREAD

**Issue by Ro-Ol** [lcosmo/DGM_pytorch#2]
Hi,
big fan of your work, but I ran into the following error while running train.py
FileNotFoundError: [Errno 2] No such file or directory: '/home/<user>/.cache/pykeops-1.4.2-cpython-38-gpu0//build-d9fa1333b1/KeOps_formula.o'

I tried to  run keops/pykeops/config.py, but without success. Could you please shed some light in how to generate that executable?
Thank you in advance

**Comment by emirceyani** [comment]
Deleted the line `sys.path.insert(0,'./keops')` in `train.py` and installed pykeops via pip and worked for me

**Comment by Ro-Ol** [comment]
Hi, thank your answer. This definitely solves the problem, but the author states in the code that the library has been modified to add gumbel noise to the probability function. 
On the other hand, I did not find any trace of this modification. Have you had any luck with that.

Thank you in advance.

**Comment by emirceyani** [comment]
I have not checked the keops modifications. If it cannot find keops, code uses the DGM module in `layers_dense.py`

**Comment by ZeinabRahbar** [comment]
> Hi Can you help me running this code as you ran it before? I am running it on colab and conflicts in version of libraries are holding me back from getting results do you know how to solve this issue?
